spring:
  profiles: default
  servlet:
    multipart:
      enabled: false
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=decola
    username: decola
    password: 'decola'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format-sql: true
server:
  port: 8080
  servlet:
    contextPath: /

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://devops.texugo.com.br:1434;databaseName=decola
    username: decola
    password: '!!!decola9!'
    
---

spring:
  profiles: prod
  servlet:
    multipart:
      enabled: false
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://banco.producao:2433;databaseName=decola
    username: decola
    password: '!!!decola9!'
server:
  port: 8081
  servlet:
    contextPath: /